robot:
  type: so101_follower
  port: /dev/ttyACM0
  id: lawson_follower_arm

  use_degrees: true
  disable_torque_on_disconnect: true

  # USB 项目默认不主动触发 calibration。
  calibrate_on_connect: false

cameras:
  top:
    type: opencv
    index_or_path: 2
    width: 640
    height: 480
    fps: 30
    fourcc: MJPG

  wrist:
    type: opencv
    index_or_path: 0
    width: 640
    height: 480
    fps: 30
    fourcc: YUYV

  side:
    type: opencv
    index_or_path: 4
    width: 640
    height: 480
    fps: 30
    fourcc: YUYV